package view;

import factory.ConexaoServidor;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

public class MIDFarm extends javax.swing.JInternalFrame {

    public MIDFarm() {
        initComponents();
        getContentPane().setBackground(java.awt.Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTempAr = new javax.swing.JTextField();
        txtUmidSolo = new javax.swing.JTextField();
        txtUmidAr = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jBtLeitura = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setBackground(new java.awt.Color(0, 0, 0));
        setClosable(true);

        jLabel1.setText("Temperatura do ar:");

        jLabel2.setText("Umidade do Solo:");

        jLabel3.setText("Umidade do Ar:");

        txtUmidSolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUmidSoloActionPerformed(evt);
            }
        });

        txtUmidAr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUmidArActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewIMG/Adobe Express - file.png"))); // NOI18N

        jBtLeitura.setText("Realizar Aferição");
        jBtLeitura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtLeituraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTempAr, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtUmidAr, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(27, 27, 27)
                                .addComponent(txtUmidSolo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(90, 90, 90)
                        .addComponent(jBtLeitura))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTempAr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUmidAr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtLeitura))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUmidSolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtLeituraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtLeituraActionPerformed
        // TODO add your handling code here:
        // Desabilita o botão enquanto a leitura está em andamento
        jBtLeitura.setEnabled(false);

        // Criando uma thread para evitar travamentos na interface
        new SwingWorker<String, Void>() {
            @Override
            protected String doInBackground() {
                return ConexaoServidor.solicitarLeitura();
            }

            @Override
            protected void done() {
                jBtLeitura.setEnabled(true); // Reativa o botão

                try {
                    String dadosSensores = get();

                    // Verifica se houve erro na conexão
                    if (dadosSensores.startsWith("Erro")) {
                        JOptionPane.showMessageDialog(MIDFarm.this, dadosSensores, "Erro", JOptionPane.ERROR_MESSAGE);
                    } else {
                        // DEBUG: Verifica a resposta recebida
                        System.out.println("Resposta do Servidor:\n" + dadosSensores);

                        // Divide a resposta do servidor corretamente
                        String[] linhas = dadosSensores.split("\n");

                        double temperatura = 0;
                        double umidadeAr = 0;
                        double umidadeSolo = 0;

                        for (String linha : linhas) {
                            linha = linha.trim();

                            if (linha.startsWith("Temperatura")) {
                                temperatura = Double.parseDouble(linha.replace("Temperatura: ", "").replace("°C", "").trim());
                                txtTempAr.setText(String.valueOf(temperatura));
                            } else if (linha.startsWith("Umidade do Ar")) {
                                umidadeAr = Double.parseDouble(linha.replace("Umidade do Ar: ", "").replace("%", "").trim());
                                txtUmidAr.setText(String.valueOf(umidadeAr));
                            }  if (linha.startsWith("Umidade do solo")) {
                                umidadeSolo = Double.parseDouble(linha.replace("Umidade do solo: ", "").replace("%", "").trim());
                                txtUmidSolo.setText(String.valueOf(umidadeSolo));
                            }
                        }

                        // DEBUG: Exibe no console os valores finais
                        System.out.println("TempAr: " + txtTempAr.getText());
                        System.out.println("UmidAr: " + txtUmidAr.getText());
                        System.out.println("UmidSolo: " + txtUmidSolo.getText());

                        double temperaturaMinima = 10;
                        double temperaturaMaxima = 35;
                        double umidadeMinima = 30;
                        double umidadeMaxima = 95;
                        double umidadeSoloMinima = 40;
                        double umidadeSoloMaxima = 90;
                        

                        // Verificar se os valores estão fora dos limites
                        if (temperatura < temperaturaMinima || temperatura > temperaturaMaxima) {
                            JOptionPane.showMessageDialog(MIDFarm.this,
                                    "Temperatura fora dos limites ideais!\n"
                                    + "Temperatura atual: " + temperatura + "°C\n"
                                    + "Limites: " + temperaturaMinima + "°C a " + temperaturaMaxima + "°C",
                                    "Alerta de Temperatura",
                                    JOptionPane.WARNING_MESSAGE);
                        }

                        if (umidadeAr < umidadeMinima || umidadeAr > umidadeMaxima) {
                            JOptionPane.showMessageDialog(MIDFarm.this,
                                    "Umidade do Ar fora dos limites ideais!\n"
                                    + "Umidade atual: " + umidadeAr + "%\n"
                                    + "Limites: " + umidadeMinima + "% a " + umidadeMaxima + "%",
                                    "Alerta de Umidade",
                                    JOptionPane.WARNING_MESSAGE);
                        }
                        
                        if (umidadeSolo < umidadeSoloMinima || umidadeSolo > umidadeSoloMaxima) {
                            JOptionPane.showMessageDialog(MIDFarm.this,
                                    "Umidade do Solo fora dos limites ideais!\n"
                                    + "Umidade atual: " + umidadeSolo + "%\n"
                                    + "Limites: " + umidadeSoloMinima + "% a " + umidadeSoloMaxima + "%",
                                    "Alerta de Umidade",
                                    JOptionPane.WARNING_MESSAGE);
                        }

                        // Passar os dados dos sensores para a classe MIDrec
                        MIDrec midrec = new MIDrec();
                        //*INSERIR UMIDADE DO SOLO (umidadeSolo)*
                        midrec.atualizarDadosSensores(temperatura, umidadeAr, umidadeSolo);

                        // Adiciona o MIDrec ao JDesktopPane (se estiver usando MDI)
                        if (getParent() instanceof JDesktopPane) {
                            JDesktopPane desktopPane = (JDesktopPane) getParent();
                            desktopPane.add(midrec);
                            midrec.setVisible(true);
                            midrec.setLocation((desktopPane.getWidth() - midrec.getWidth()) / 2,
                                    (desktopPane.getHeight() - midrec.getHeight()) / 2);
                        }
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(MIDFarm.this, "Erro ao processar leitura: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }

        }
                .execute();

    }//GEN-LAST:event_jBtLeituraActionPerformed

    private void txtUmidArActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUmidArActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUmidArActionPerformed

    private void txtUmidSoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUmidSoloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUmidSoloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtLeitura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtTempAr;
    private javax.swing.JTextField txtUmidAr;
    private javax.swing.JTextField txtUmidSolo;
    // End of variables declaration//GEN-END:variables
}
