/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import factory.ConexaoServidor;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author Cliente
 */
public class MIDFarm extends javax.swing.JInternalFrame {

    /**
     * Creates new form MIDFarm
     */
    public MIDFarm() {
        initComponents();
        getContentPane().setBackground(java.awt.Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTempAr = new javax.swing.JTextField();
        txtUmidSolo = new javax.swing.JTextField();
        txtUmidAr = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jBtLeitura = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setClosable(true);

        jLabel1.setText("Temperatura do ar:");

        jLabel2.setText("Umidade do Solo:");

        jLabel3.setText("Umidade do Ar:");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewIMG/Adobe Express - file.png"))); // NOI18N

        jBtLeitura.setText("Realizar Aferição");
        jBtLeitura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtLeituraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(66, 66, 66))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(72, 72, 72)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtUmidAr, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtLeitura)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTempAr, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUmidSolo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTempAr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtLeitura)
                    .addComponent(jLabel3)
                    .addComponent(txtUmidAr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUmidSolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtLeituraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtLeituraActionPerformed
        // TODO add your handling code here:
        // Desabilita o botão enquanto a leitura está em andamento
        jBtLeitura.setEnabled(false);

        // Criando uma thread para evitar travamentos na interface
        new SwingWorker<String, Void>() {
            @Override
            protected String doInBackground() {
                return ConexaoServidor.solicitarLeitura();
            }

            @Override
            protected void done() {
                jBtLeitura.setEnabled(true); // Reativa o botão

                try {
                    String dadosSensores = get();

                    // Verifica se houve erro na conexão
                    if (dadosSensores.startsWith("Erro")) {
                        JOptionPane.showMessageDialog(MIDFarm.this, dadosSensores, "Erro", JOptionPane.ERROR_MESSAGE);
                    } else {
                        // DEBUG: Verifica a resposta recebida
                        System.out.println("Resposta do Servidor:\n" + dadosSensores);

                        // Divide a resposta do servidor corretamente
                        String[] linhas = dadosSensores.split("\n");

                        for (String linha : linhas) {
                            linha = linha.trim();
                            
                            if (linha.startsWith("Temperatura")) {
                                txtTempAr.setText(linha.replace("Temperatura: ", "").replace("°C", "").trim());
                            } else if (linha.startsWith("Umidade do Ar")) {
                                txtUmidAr.setText(linha.replace("Umidade do Ar: ", "").replace("%", "").trim());
                            } else if (linha.toLowerCase().contains("umidade do solo") || linha.toLowerCase().contains("solo")) {  
                                txtUmidSolo.setText(linha.replace("Umidade do solo: ", "").replace("%", "").trim());
                            }
                        }

                        // DEBUG: Exibe no console os valores finais
                        System.out.println("TempAr: " + txtTempAr.getText());
                        System.out.println("UmidAr: " + txtUmidAr.getText());
                        System.out.println("UmidSolo: " + txtUmidSolo.getText());
                        
                        // Passar os dados dos sensores para a classe MIDrec
                    double temperatura = Double.parseDouble(txtTempAr.getText());
                    double umidadeAr = Double.parseDouble(txtUmidAr.getText());
                    //double umidadeSolo = Double.parseDouble(txtUmidSolo.getText());

                    MIDrec midrec = new MIDrec();
                    midrec.atualizarDadosSensores(temperatura, umidadeAr);
                    midrec.setVisible(true);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(MIDFarm.this, "Erro ao processar leitura: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }

        }
                .execute();

    }//GEN-LAST:event_jBtLeituraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtLeitura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtTempAr;
    private javax.swing.JTextField txtUmidAr;
    private javax.swing.JTextField txtUmidSolo;
    // End of variables declaration//GEN-END:variables
}
